apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose --file ngc.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: bsf
  name: bsf
spec:
  containers:
    - args:
        - open5gs-bsfd
      image: gradiant/open5gs:2.7.1
      name: bsf
      volumeMounts:
        - mountPath: /opt/open5gs/etc/open5gs/bsf.yaml
          name: bsf-cm0
          subPath: bsf.yaml
  restartPolicy: OnFailure
  volumes:
    - configMap:
        items:
          - key: bsf.yaml
            path: bsf.yaml
        name: bsf-cm0
      name: bsf-cm0
