apiVersion: v1
kind: Service
metadata:
  name: gnb-service
spec:
  selector:
    app: ueransim
  ports:
    - name: sctp
      port: 38412
      targetPort: 38412
      protocol: SCTP
    - name: gtp
      port: 2152
      targetPort: 2152
      protocol: UDP
    - name: rls
      port: 4997
      targetPort: 4997
      protocol: UDP

