apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f ngc.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  containers:
    - name: grafana
      image: grafana/grafana:12.0.1
      env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "1234"
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_PATHS_PROVISIONING
          value: /etc/grafana/provisioning
      ports:
        - containerPort: 3000
          protocol: TCP
      volumeMounts:
        - name: grafana-dashboard
          mountPath: /etc/grafana/provisioning/dashboards/my-dashboard.json
          subPath: my-dashboard.json
        - name: grafana-config
          mountPath: /etc/grafana/provisioning/dashboards/dashboard.yaml
          subPath: dashboard.yaml
        - name: grafana-datasource
          mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
          subPath: datasource.yaml

  restartPolicy: OnFailure

  volumes:
    - name: grafana-dashboard
      configMap:
        name: grafana
        items:
          - key: my-dashboard.json
            path: my-dashboard.json

    - name: grafana-config
      configMap:
        name: dashboard-config
        items:
          - key: dashboard.yaml
            path: dashboard.yaml

    - name: grafana-datasource
      configMap:
        name: dashboard-datasource
        items:
          - key: datasource.yaml
            path: datasource.yaml

