apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-config
data:
  dashboard.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 10
        options:
          path: /etc/grafana/provisioning/dashboards

