apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose --file ngc.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nssf
  name: nssf
spec:
  containers:
    - args:
        - open5gs-nssfd
      image: gradiant/open5gs:2.7.1
      name: nssf
      volumeMounts:
        - mountPath: /opt/open5gs/etc/open5gs/nssf.yaml
          name: nssf-cm0
          subPath: nssf.yaml
  restartPolicy: OnFailure
  volumes:
    - configMap:
        items:
          - key: nssf.yaml
            path: nssf.yaml
        name: nssf-cm0
      name: nssf-cm0
