apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: amf
        fallback_scrape_protocol: PrometheusText0.0.4
        static_configs:
          - targets: ["amf:9090"]
      - job_name: pcf
        fallback_scrape_protocol: PrometheusText0.0.4
        static_configs:
          - targets: ["pcf:9090"]
      - job_name: smf
        fallback_scrape_protocol: PrometheusText0.0.4
        static_configs:
          - targets: ["smf:9090"]
      - job_name: upf
        fallback_scrape_protocol: PrometheusText0.0.4
        static_configs:
          - targets: ["upf:9090"]
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: prometheus
  name: prometheus-config
