apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose --file ngc.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: smf
  name: smf
spec:
  containers:
    - args:
        - open5gs-smfd
      image: gradiant/open5gs:2.7.1
      name: smf
      volumeMounts:
        - mountPath: /opt/open5gs/etc/open5gs/smf.yaml
          name: smf-cm0
          subPath: smf.yaml
  restartPolicy: OnFailure
  volumes:
    - configMap:
        items:
          - key: smf.yaml
            path: smf.yaml
        name: smf-cm0
      name: smf-cm0
