apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose --file ngc.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: udm
  name: udm
spec:
  containers:
    - args:
        - open5gs-udmd
      image: gradiant/open5gs:2.7.1
      name: udm
      volumeMounts:
        - mountPath: /opt/open5gs/etc/open5gs/udm.yaml
          name: udm-cm0
          subPath: udm.yaml
  restartPolicy: OnFailure
  volumes:
    - configMap:
        items:
          - key: udm.yaml
            path: udm.yaml
        name: udm-cm0
      name: udm-cm0
