apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose --file ngc.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: amf
  name: amf
spec:
  nodeSelector:
    kubernetes.io/hostname: k3d-open5gs-cluster-agent-0
#  hostNetwork: true
#  dnsPolicy: "ClusterFirstWithHostNet"
  containers:
    - args:
        - open5gs-amfd
      image: gradiant/open5gs:2.7.1
      name: amf
      ports:
        - containerPort: 38412
          hostPort: 38412
          protocol: SCTP
      volumeMounts:
        - mountPath: /opt/open5gs/etc/open5gs/amf.yaml
          name: amf-cm0
          subPath: amf.yaml
  restartPolicy: OnFailure

  volumes:
    - configMap:
        items:
          - key: amf.yaml
            path: amf.yaml
        name: amf-cm0
      name: amf-cm0
