apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose --file ngc.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ausf
  name: ausf
spec:
  containers:
    - args:
        - open5gs-ausfd
      image: gradiant/open5gs:2.7.1
      name: ausf
      volumeMounts:
        - mountPath: /opt/open5gs/etc/open5gs/ausf.yaml
          name: ausf-cm0
          subPath: ausf.yaml
  restartPolicy: OnFailure
  volumes:
    - configMap:
        items:
          - key: ausf.yaml
            path: ausf.yaml
        name: ausf-cm0
      name: ausf-cm0
