{
 "title": "Test Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "AMF Requests",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "fivegs_amffunction_amf_authreq{} \n- \n fivegs_amffunction_amf_authreject{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_amffunction_amf_authreject{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMF Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "amf_session{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# ACTIVE UE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ues_active{}", "legendFormat": "__auto" }
   ]
  }
 ]
}