apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f ngc.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  containers:
    - env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "1234"
        - name: GF_SECURITY_ADMIN_USER
          value: admin
      image: grafana/grafana:12.0.1
      name: grafana
      ports:
        - containerPort: 3000
          protocol: TCP
  restartPolicy: OnFailure
