apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose --file ngc.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nrf
  name: nrf
spec:
  containers:
    - args:
        - open5gs-nrfd
      image: gradiant/open5gs:2.7.1
      name: nrf
      volumeMounts:
        - mountPath: /opt/open5gs/etc/open5gs/nrf.yaml
          name: nrf-cm0
          subPath: nrf.yaml
  restartPolicy: OnFailure
  volumes:
    - configMap:
        items:
          - key: nrf.yaml
            path: nrf.yaml
        name: nrf-cm0
      name: nrf-cm0
