apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose --file ngc.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: scp
  name: scp
spec:
  containers:
    - args:
        - open5gs-scpd
      env:
        - name: DB_URI
          value: mongodb://mongo/open5gs
      image: gradiant/open5gs:2.7.1
      name: scp
      volumeMounts:
        - mountPath: /opt/open5gs/etc/open5gs/scp.yaml
          name: scp-cm0
          subPath: scp.yaml
  restartPolicy: OnFailure
  volumes:
    - configMap:
        items:
          - key: scp.yaml
            path: scp.yaml
        name: scp-cm0
      name: scp-cm0
