apiVersion: v1
kind: ConfigMap
metadata:
  name: smf-cm0
  labels:
    io.kompose.service: smf
  annotations:
    use-subpath: "true"
data:
  smf.yaml: |
    logger:
      file:
        path: /opt/open5gs/var/log/open5gs/smf.log
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
    # max:
    #   ue: 1024
    #   peer: 64

    smf:
      sbi:
        server:
          - dev: eth0
            port: 7777
        client:
          # nrf:
          #   - uri: http://127.0.0.10:7777
          scp:
            - uri: http://scp:7777
      pfcp:
        server:
          - dev: eth0
        client:
          upf:
            - address: upf
      gtpc:
        server:
          - dev: eth0
      gtpu:
        server:
          - dev: eth0
      metrics:
        server:
          - dev: eth0
            port: 9090
      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1
      dns:
        - 8.8.8.8
        - 8.8.4.4
      mtu: 1400
      ctf:
        enabled: auto # auto(default)|yes|no

    # Example of SBI Server override
    # sbi:
    #   server:
    #     - dev: eth0
    #       advertise: open5gs-smf.svc.local

    # Example of PFCP Server advertise
    # pfcp:
    #   server:
    #     - dev: eth0
    #       advertise: open5gs-smf.svc.local

    # DNN-based session pools (optional examples)
    # session:
    #   - subnet: 10.45.0.1/16
    #     dnn: internet
    #   - subnet: 2001:db8:cafe::1/48
    #     dnn: internet
    #   - subnet: 10.46.0.1/16
    #     dnn: ims
    #   - subnet: 2001:db8:babe::1/48
    #     dnn: ims

    # Range-based session allocation (optional example)
    # session:
    #   - subnet: 10.45.0.1/16
    #     range:
    #       - 10.45.0.100-10.45.0.200
    #       - 10.45.1.100-
    #       - -10.45.0.200

    # Advanced examples for info, selection and TAI mapping can go here...
    # Uncomment and configure as needed.

