apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ngc.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: udr
  name: udr
spec:

  ports:
    - name: "sbi"
      port: 7777
      targetPort: 7777
  selector:
    io.kompose.service: udr
