apiVersion: v1
kind: Service
metadata:
  name: upf
spec:
  type: ClusterIP
  selector:
    io.kompose.service: upf
  ports:
    - name: "pfcp"
      port: 8805
      targetPort: 8805
    - name: "sbi"
      protocol: TCP
      port: 7777
      targetPort: 7777
    - name: "metrics"
      protocol: TCP
      port: 9090
      targetPort: 9090
