apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ngc.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: upf
  name: upf
spec:
  type: NodePort
  ports:
    - name: "2152"
      port: 2152
      protocol: UDP
      targetPort: 2152
      nodePort: 30003
    - name: 2152-tcp
      port: 2152
      targetPort: 2152
      nodePort: 30002
    - name: "8805"
      protocol: UDP
      port: 8805
      targetPort: 8805
    - name: "sbi"
      protocol: TCP
      port: 7777
      targetPort: 7777
    - name: "metrics"
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    io.kompose.service: upf
