apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose --file ngc.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: upf
  name: upf
spec:
  containers:
    - args:
        - open5gs-upfd
      image: gradiant/open5gs:2.7.1
      name: upf
      ports:
        - containerPort: 2152
          protocol: UDP
        - containerPort: 2152
          protocol: TCP
        - containerPort: 8805
          protocol: TCP
      securityContext:
        capabilities:
          add:
            - all
        privileged: true
      volumeMounts:
        - mountPath: /opt/open5gs/etc/open5gs/upf.yaml
          name: upf-cm0
          subPath: upf.yaml
  restartPolicy: OnFailure
  volumes:
    - configMap:
        items:
          - key: upf.yaml
            path: upf.yaml
        name: upf-cm0
      name: upf-cm0
