apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose --file ngc.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: webui
  name: webui
spec:
  restartPolicy: OnFailure
  initContainers:
  - name: wait-for-mongodb
    image: mongo:6.0
    command:
      [
        "sh",
        "-c",
        'until mongosh --host mongo --eval "db.adminCommand(\"ping\")" > /dev/null 2>&1; do echo "Waiting for MongoDB to be ready..."; sleep 2; done; echo "MongoDB is ready!"'
      ]
  containers:
    - name: webui
      image: gradiant/open5gs-webui:2.7.1
      env:
        - name: DB_URI
          value: mongodb://mongo/open5gs
        - name: NODE_ENV
          value: dev
      ports:
        - containerPort: 9999
          protocol: TCP

