apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ngc.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: webui
  name: webui
spec:
  type: NodePort
  ports:
    - name: "9999"
      port: 9999
      targetPort: 9999
      nodePort: 30000
  selector:
    io.kompose.service: webui
